name: ci
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        env:
          TAG: ${GITHUB_REF##*/}.${{github.run_number}}
        run: |
          docker build -t test-image:${{ env.TAG }} .
          echo "::set-output name=tag::${GITHUB_REF##*/}.${{github.run_number}}"
        id: docker_build

      - name: Tag body
        run: |
          echo "::set-output name=body::$(git log -1 --oneline)"
        id: body

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.docker_build.outputs.tag }}
          body: ${{ steps.body.outputs.body }}
          file: |
            README.md
