name: ci
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        env:
          TAG: ${GITHUB_REF##*/}.${{github.run_number}}
        run: |
          docker build -t test-image:${{ env.TAG }} .

