name: ci
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: Build
        env:
          TAG: ${GITHUB_REF##*/}.${{github.run_number}}
        run: |
          # docker build -t test-image:${{ env.TAG }} .
          echo "::set-output name=tag::${GITHUB_REF##*/}.${{github.run_number}}"
        id: build

      - name: Tag
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.tag }}
