---
on:
  pull_request:
    types: [opened, closed, reopened, edited]

jobs:
  print_info:
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Action=${{ github.event.action }}"
