---
name: Protobuf Linter
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup buf
        uses: wizhi/setup-buf@v1
        with:
          version: 0.43.2

      - name: Protobuf lint
        run: buf lint

      - name: Breaking changes check
        if: github.ref != 'refs/heads/master'
        run: >-
          buf breaking
          --against ".git#ref=${{ github.base_ref }}"
