---
name: Release via gh cli

"on":
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Get next release
        uses: cycjimmy/semantic-release-action@v3
        id: next-release
        with:
          semantic_version: 19.0.5
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update env
        run: |
          {
            echo "has_release=${{ steps.next-release.outputs.new_release_published }}"
            echo "new_version=v${{ steps.next-release.outputs.new_release_version }}"
            echo "new_major_version=v${{ steps.next-release.outputs.new_release_major_version }}"
          } >> "$GITHUB_ENV"

      - name: Tag commit
        if: ${{ env.has_release == 'true' }}
        run: |
          echo "[info] configure committer"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "[info] tag latest commit with ${{ env.new_version }}"
          git tag --annotate "${{ env.new_version }}" --message "${{ env.new_version }}"

          echo "[info] move major tag ${{ env.new_major_version }} to the latest commit"
          git tag --annotate "${{ env.new_major_version }}" --message "${{ env.new_major_version }}" --force

          git log --format="%H %s %d"

          echo "[info] push version tag ${{ env.new_version }}"
          git push origin "${{ env.new_version }}"

          echo "[info] push major version tag ${{ env.new_major_version }}"
          git push origin "${{ env.new_major_version }}" --force

      - name: Create release
        if: ${{ env.has_release == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh release create "${{ env.new_version }}" --generate-notes --latest --target master
