---
name: Run shell commands
"on":
  push:
    branches:
      - "${{ github.event.repository.default_branch }}"
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      list: ("value-1" "value-2" "value-3")
      multi: >
        (
          "multi-1"
          "multi-2"
          "multi-3"
        )
    steps:
      - run: |
          env | sort

      - uses: actions/checkout@v4
        with:
          ref: "$GITHUB_REF_NAME"

      - run: |
          echo "Run on event ${{ github.event_name }}"

          env

          values=${{ env.list }}
          for value in "${values[@]}"; do
            echo "::notice Value::$value"
          done

          values=${{ env.multi }}
          for value in "${values[@]}"; do
            echo "::notice Multi::$value"
          done

      - run: |
          yq --help

          echo $(yq eval-all -Nr '.spec.values.image.tag' .github/test/yq-test.yaml | uniq)
