---
name: Tag latest release
on:
  release:
    types:
      - "published"

jobs:
  tag_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          fetch-depth: 0

      - run: |
          version="${GITHUB_REF#refs/tags/}"
          major_version=${version%%.*}
          echo "this release $GITHUB_REF major version is: $major_version"

          echo -e "\nconfigure commiter"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo -e "\nre-tag major version"
          git tag --annotate "$major_version" --message "$major_version" --force
          git push origin "$major_version" --force

          echo "::notice title=Re-tag major version::$major_version"
