---
name: Setup Node + JDK

"on":
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node -v

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          java --version
          node -v
