---
name: Test push with commit key
"on":
  push:
    branches:
      - "master"

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Check for next release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: '19.0.5'
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push update
        if: ${{ steps.semantic.outputs.new_release_published != 'true' }}
        run: |
          echo "configure commiter"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          [[ ! -e Changelog.md ]] && echo "# Changelog" > Changelog.md

          echo "" >> Changelog.md
          echo "$(git log -n1)" >> Changelog.md
          git add Changelog.md
          git commit -m "docs: update changelog"

          echo "push to remote"
          git push origin HEAD
