---
name: GitHub Action Trigger
on:
  push:
    branches:
      - "master"
    paths:
      - "foo/bar1/**"
jobs:
  github-action-trigger:
    runs-on: ubuntu-latest
    env:
      dir: "foo/bar1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect dir changes
        id: dir-changed
        run: |
          git log -m --name-only -n1
          git diff --name-only --diff-filter=d HEAD HEAD~1
          git diff --name-only --diff-filter=d HEAD HEAD~1 | grep "${{ env.dir }}"
          directory=""
          for f in $(git diff --name-only --diff-filter=d HEAD HEAD~1 | grep "${{ env.dir }}"); do
            directory=$(dirname $f)
          done
          echo "directory: $directory"
          echo "dir=$directory" >> "$GITHUB_OUTPUT"

      - name: Output
        run: |
          echo "::notice title=Output::${{ steps.dir-changed.outputs.dir }}"
