---
name: Lint YAML using https://github.com/karancode/yamllint-github-action
on:
  push:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  yamllint_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        id: lint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: ./yamllint-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
