---
name: Lint YAML
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  yamllint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        id: lint
        uses: beiertu-mms/yamllint-composite-action@v1.2.0
        with:
          config_data: "{extends: default, rules: {line-length: {max: 120}}}"
          file_or_dir: ./yamllint-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo -e "\nYamllint result:\n${{ steps.lint.outputs.lint_output }}"
        if: ${{ always() }}

  yamllint_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        id: lint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: ./yamllint-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
