---
name: Lint YAML
on:
  push:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  yamllint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: beiertu-mms/yamllint-composite-action@v1.1.1
        with:
          config_data: '{extends: default, rules: {line-length: {max: 120}}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
